/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState } from "react";
import Head from "next/head";

//data
import courses from "../data/courses.json";

//components
import Carousel from "../components/carousel/Carousel";
import WriteAnimation from "../components/writeAnimation/WriteAnimation";
import Course from "../components/course/Course";

export default function Home() {
  const headerRef = useRef(null);
  const coursesRef = useRef(null);

  useEffect(() => {
    //fade-in of the header elements
    headerRef.current.querySelectorAll(":scope > *").forEach((el, i) => {
      el.classList.add("fade-in");
      el.style.animationDelay = `${i / 3 + 0.5}s`;
    });
    //slide-in of the courses elements
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("move-center");
        }
      });
    }, {});
    coursesRef.current
      .querySelectorAll(".move-left, .move-right")
      .forEach((el) => {
        observer.observe(el);
      });
  }, []);
  return (
    <div>
      <Head>
        <title>Kris Heijnen - Web Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        {/* HEADER */}
        <header className="header" ref={headerRef}>
          <div className="my-name-is">Hi, my name is</div>
          <h1>Kris Heijnen</h1>
          <div className="avatar">
            <img src="/avatar.png" alt="kris heijnen" />
          </div>
          <h4 className="mono">
            <WriteAnimation sentence="And I love coding..." delay={2000} />
          </h4>
        </header>
        {/* PROJECTS */}
        <section className="projects">
          <h2 className="projects__title">-Projects-</h2>
          <div className="mobile">
            <Carousel />
          </div>
          <div className="cards">
            <div className="card">
              <img src="/joao-mobile.png" alt={""}></img>
              <p>
                A website I created for João Vedana, a musician. It is built
                with <strong className="mono normalize">NextJS</strong> and a
                CMS called Sanity. The system is set up in a way that whenever
                the content changes Vercel creates new static files to be
                served, which provides for a fast load time and makes it
                SEO-friendly. <br />
                <a href="https://www.joaovedana.com/">
                  https://www.joaovedana.com
                </a>
              </p>
            </div>
          </div>
        </section>
        {/* COURSES */}
        <section className="courses">
          <h2 className="courses__title">-Courses-</h2>
          <div className="courses__wrapper" ref={coursesRef}>
            {courses.map((course) => {
              return (
                <Course
                  title={course.title}
                  date={course.date}
                  key={course.title}
                >
                  {course.description}
                </Course>
              );
            })}
          </div>
        </section>
      </main>

      <footer></footer>
    </div>
  );
}
