/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef } from "react";
import Head from "next/head";

//data
import courses from "../data/courses.json";

//components
import Carousel from "../components/carousel/Carousel";
import WriteAnimation from "../components/writeAnimation/WriteAnimation";
import Course from "../components/course/Course";
import ObserverComponent from "../components/observerComponent/ObserverComponent";

export default function Home() {
  const headerRef = useRef(null);
  const coursesRef = useRef(null);
  useEffect(() => {
    // fade-in of the header elements
    headerRef.current.querySelectorAll(":scope > *").forEach((el, i) => {
      el.classList.add("fade-in");
      el.style.animationDelay = `${i / 3 + 0.5}s`;
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Kris Heijnen - Web Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        {/* HEADER */}
        <header className="header">
          <div className="header__wrapper" ref={headerRef}>
            <div className="my-name-is">Hi, my name is</div>
            <h1>Kris Heijnen</h1>
            <div className="avatar">
              <img src="/avatar.png" alt="kris heijnen" />
            </div>
            <h4 className="mono">
              <WriteAnimation sentence="And I love coding..." delay={2000} />
            </h4>
          </div>
        </header>
        {/* PROJECTS */}
        <section className="projects">
          <h2 className="projects__title">-Projects-</h2>
          <div className="mobile">
            <Carousel />
          </div>
          <div className="cards">
            <div className="card">
              <img src="/joao-mobile.png" alt={""}></img>
              <p>
                A website I created for João Vedana, a musician. It is built
                with <strong className="mono normalize">NextJS</strong> and a
                CMS called Sanity. The system is set up in a way that whenever
                the content changes Vercel creates new static files to be
                served, which provides for a fast load time and makes it
                SEO-friendly. <br />
                <a href="https://www.joaovedana.com/">
                  https://www.joaovedana.com
                </a>
              </p>
            </div>
          </div>
        </section>
        {/* COURSES */}
        <section className="courses">
          <h2 className="courses__title">-Courses-</h2>
          <div className="courses__wrapper" ref={coursesRef}>
            {courses.map((course, index) => {
              const observerOptions = {
                threshold: "1.0",
              };
              return (
                <>
                  <ObserverComponent
                    addClass={["fade-in-course"]}
                    options={observerOptions}
                    key={course.title}
                  >
                    <Course
                      title={course.title}
                      date={course.date}
                      lastOfArray={index == courses.length - 1}
                    >
                      {course.description}
                    </Course>
                  </ObserverComponent>
                </>
              );
            })}
          </div>
        </section>
      </main>

      <footer></footer>
    </div>
  );
}
